# Generated by Django 3.0.5 on 2020-04-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=115, null=True)),
                ('edit_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', markdownx.models.MarkdownxField(blank=True, default='', max_length='10000')),
                ('protection', models.CharField(choices=[('NO', 'None'), ('LO', 'Locked'), ('CO', 'Confirmed Users Only')], default='NO', help_text='What kind of protection does this page have?', max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='wiki.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=115, null=True)),
                ('edit_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', markdownx.models.MarkdownxField(blank=True, default='', max_length='10000')),
                ('edit_number', models.PositiveSmallIntegerField(default=0)),
                ('current', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='wiki.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='unique_page_title'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_page_slug'),
        ),
    ]
