# Generated by Django 3.0.5 on 2020-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='protection',
            field=models.CharField(choices=[('NO', 'None'), ('LO', 'Locked'), ('NC', "Locked and doesn't allow children"), ('CO', 'Confirmed Users Only')], default='NO', help_text="Setting the protection to 'locked' will not allow others to edit this page in the future.", max_length=2),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
