# Generated by Django 3.0.5 on 2020-04-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200426_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['current', 'created_date']},
        ),
    ]
