# Generated by Django 3.0.5 on 2020-04-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20200428_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ManyToManyField(related_name='report_reason', to='wiki.ReportReason'),
        ),
    ]
