# Generated by Django 3.0.5 on 2020-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20200428_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportreason',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='page',
            name='helper_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ManyToManyField(to='wiki.ReportReason'),
        ),
    ]
